markdown: kramdown
permalink: /:year/:month/:day/:title/
url: http://whirlyminds2020.github.io
podcast_url: https://jt.ximalaya.com
author: "意马心猿 Whirly Minds"
highlighter: rouge
exclude: ["Rakefile", "CNAME", "README.md"]
safe: false
paginate: 10

# Gems
plugins:
  - audioinfo
  - jekyll-paginate
